### ISSUE TITLE
UTF-8 error, when using the dropbox database.

### ISSUE THREAD

**Issue by FreezyExp** [dndtools/docker#1]
Caught OperationalError while rendering: Could not decode to UTF-8 column 'name' with text 'Monster Compendium: Monsters of Faer�n'

Fixing this might lead to other issues, so posting it here in hopes it's a silly config problem in the docker setup.

**Comment by antoinealb** [comment]
I think the Dropbox database is dumped from mysql, which can use other
encodings such as Latin 1. I have no idea how to convert it though.

**Comment by Jadaw1n** [comment]
This worked for me:
`echo '.dump' | sqlite3 existing.sqlite | iconv -f "windows-1252" -t "UTF-8" | sqlite3 new.sqlite`

**Comment by FreezyExp** [comment]
It should be noted that sqlite3 is not loaded in this docker (also not in my boot2docker)

First stop the dndtools docker, so the sqlite is not in use while we convert it.
`docker ps`
`docker stop <name of your dndtools>`

Thus I will need to start a temporary docker aimed at conversion

using the same linux version as the docker, so you already have the image
`docker run -v /mnt/sda/var/sqlite:/data/sqlite -it debian:stable`

Install sqlite3:
`apt-get update && apt-get -y install sqlite3 libsqlite3-dev`

Then cd into the proper dir
`cd /data/sqlite/`
here you should find the dndtools.sqlite

Backup the old database:
`mv  dndtools.sqlite dndtools.sqlite.old`

Next up Jadaw1n's conversion:
`echo '.dump' | sqlite3 dndtools.sqlite.old | iconv -f "windows-1252" -t "UTF-8" | sqlite3 dndtools.sqlite`

exit the docker
`exit`

restart the dndtools docker
`docker start <name of your dndtools>`

Cleanup:
remove the temporary container we just used for conversion
`docker ps -a`
`docker rm <name of temp converion container>`

Looking good now, thanks Jadaw1n!
