### ISSUE TITLE
dndproject/local.py

### ISSUE THREAD

**Issue by FreezyExp** [dndtools/docker#2]
since a few days ago
local.py is now located in root instead of dndproject/local.py

**Comment by Jadaw1n** [comment]
Hu? Latest commit is from me about two weeks ago. I adjusted the path to the local.py to comply with the new changes.

**Comment by FreezyExp** [comment]
I see it now, weird I could have sworn the files I got did not have the alterations.

**Comment by FreezyExp** [comment]
other issue, local.py appears as a folder not as a file.
presumably because the local.py folder is created in the docker script, instead of copying the included file?

removing the folder and uploading the local.py resolves the issue.

**Comment by Jadaw1n** [comment]
If the file does not exist (at runtime), a symbolic link is created which points to /data/local.py. Are you sure it's a folder and not a symlink?

**Comment by FreezyExp** [comment]
The symlink didn't work properly in filezilla, it showed as a folder symlink instead of an editable file.
It also did not find the target file, and the settings it set (import \* from local) did not seem to work either, instead it was using local.py.sample (I think).

I also just found DATA_DIR defined in the docker file. sorry for being a newbie on all this docker stuff, I only recently started working with it. 

From this I deduce that it is preferable to configure the docker run command to mount the entire /data as a volume and rigging the script to add missing files. Is this correct?
Would this also grab the runscript and local.py files if they are missing?

This way settings and the database would be in a single data folder somewhere on the host, which sounds very logical.

Tweaking the wget https://github.com/dndtools/dndtools/archive/$DNDTOOLS_VERSION.tar.gz with a parameter so it can also grab the user's repo would be a nice one as well.

ENV DNDTOOLS_GITREPO https://github.com/dndtools/dndtools/archive/
wget $DNDTOOLS_GITREPO/$DNDTOOLS_VERSION.tar.gz

thanks for all your work, highly appreciated.
I will update the wiki entry, once I get everything right and easy.

**Comment by Jadaw1n** [comment]
Strange. Can you look at it in a shell?
The .sample file is certainly not used. 

If you want to use your own dndtools version I recommend you to separatly git clone it, and link it like described here: https://github.com/dndtools/docker#with-your-own-dndtools-version-for-development
With your approach you have to recompile the docker image everytime you update your repository (which is unbearably slow for development).
Since you use boot2docker, you should figure out how to share folders from your host machine into boot2docker (and then into docker itself). This would eliminate the need for FileZilla altogether.

> From this I deduce that it is preferable to configure the docker run command to mount the entire /data as a volume and rigging the script to add missing files. Is this correct?

You can mount it as a volume. But the only files that reside there are the local.py, the linked sqlite and the runscript. What additional files would you want to put into /data?

>  Would this also grab the runscript and local.py files if they are missing?

No. If you create a volume there, then all the existing files in this folder aren't visible anymore.

**Comment by FreezyExp** [comment]
I'm now using boot2docker, the complete setup is:

sudo su 
mkdir /mnt/sda1/data
chmod -r 777 /mnt/sda1/data/
- upload sqlite folder containing the sqlite data, local.py and runscript.sh
- upload www folder with my dndtools repo, with some additional tweaks to remove facebook

we need to do this again, so that the docker can actually edit / execute the files  #byebyesecurity
chmod -r 777 /mnt/sda1/data/

docker run --restart=always -p 8000:8000 -it\
  --name="dndtools" \
  -v /mnt/sda1/data/sqlite/:/data/ \
  -v /mnt/sda1/data/www/:/dndtoolsrepo/ \
  -e RECAPTCHA_PUBLIC="<publickey>" \
  -e RECAPTCHA_PRIVATE="<privatekey>" \
  dndtools/dndtools:master

and this works for me :-)
in the wiki I recommended creating a separate storage volume, but /mnt/sda1/data/ can be used directly in sftp, so if security is not an issue (sftp only over host only network) then this is fine.

Alternatively the second chmod can also be done in filezilla, just grant 777 recursively on the /mnt/sda1/data/

**Comment by FreezyExp** [comment]
yup found out that the symlink is going to the volume inside the docker, which is why the sftp can not follow it, it does not have the proper rights.

Either way, solving this by supplying the entire /data/ folder as a volume solved more desires I had (like a place to create backups/patches).
It is worth the manual upload.
